#!/usr/bin/env python3
"""Run the reproducible ASTRA-OS software assurance workflow.

The default workflow executes the existing full verification campaign, an
ASan/UBSan build and test pass, the controlled mutation check, and provenance
manifest generation. A compact machine-readable summary and per-stage logs are
written under reports/latest/.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = REPO_ROOT / "reports" / "latest"
SUMMARY_PATH = REPORT_DIR / "assurance_summary.json"
MANIFEST_PATH = REPORT_DIR / "baseline_manifest.json"
CHECK_SOURCE_CLEANLINESS = REPO_ROOT / "tools" / "check_source_cleanliness.py"


@dataclass
class StageResult:
    name: str
    command: list[str]
    return_code: int
    started_at_utc: str
    finished_at_utc: str
    log_path: str

    @property
    def passed(self) -> bool:
        return self.return_code == 0


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def safe_stage_name(name: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in name).strip("_")


def run_stage(
    name: str,
    command: Sequence[str],
    *,
    environment: dict[str, str] | None = None,
) -> StageResult:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    log_path = REPORT_DIR / f"{safe_stage_name(name)}.log"
    started_at = utc_now()

    print()
    print(f"== {name} ==")
    print("+", " ".join(command))

    merged_environment = os.environ.copy()
    if environment:
        merged_environment.update(environment)

    with log_path.open("w", encoding="utf-8") as log:
        process = subprocess.Popen(
            list(command),
            cwd=REPO_ROOT,
            env=merged_environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
            log.write(line)
        return_code = process.wait()

    result = StageResult(
        name=name,
        command=list(command),
        return_code=return_code,
        started_at_utc=started_at,
        finished_at_utc=utc_now(),
        log_path=str(log_path.relative_to(REPO_ROOT)),
    )
    print(f"[{ 'PASS' if result.passed else 'FAIL' }] {name}")
    return result


def write_summary(
    results: list[StageResult],
    *,
    overall_status: str,
    requested_quick_mode: bool,
) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "astra-os.assurance-summary.v1",
        "generated_at_utc": utc_now(),
        "overall_status": overall_status,
        "quick_mode": requested_quick_mode,
        "stages": [
            {
                **asdict(result),
                "passed": result.passed,
            }
            for result in results
        ],
    }
    SUMMARY_PATH.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def generate_manifest(
    *,
    verification_status: str,
    commands: list[list[str]],
    sanitizers_enabled: bool,
) -> int:
    command = [
        sys.executable,
        str(REPO_ROOT / "tools" / "generate_baseline_manifest.py"),
        "--output",
        str(MANIFEST_PATH),
        "--verification-status",
        verification_status,
        "--build-type",
        "Debug",
        "--warnings-as-errors",
        "--note",
        "Generated by tools/run_astra_os_assurance.py.",
    ]
    if sanitizers_enabled:
        command.append("--sanitizers-enabled")
    for executed_command in commands:
        command.extend(["--test-command", " ".join(executed_command)])

    completed = subprocess.run(command, cwd=REPO_ROOT, check=False, text=True)
    return completed.returncode


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--quick",
        action="store_true",
        help="Run the full existing verification suite but skip sanitizer and mutation stages.",
    )
    parser.add_argument("--build-dir", default="build")
    parser.add_argument(
        "--skip-monte-carlo",
        action="store_true",
        help="Forward --skip-monte-carlo to the existing full verification runner.",
    )
    parser.add_argument(
        "--skip-pi-package",
        action="store_true",
        help="Forward --skip-pi-package to the existing full verification runner.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    results: list[StageResult] = []
    commands_executed: list[list[str]] = []
    sanitizer_requested = not args.quick
    overall_status = "passed"

    full_verification_command = [
        sys.executable,
        str(REPO_ROOT / "tools" / "run_all_scenarios.py"),
        "--build-dir",
        args.build_dir,
    ]
    if args.skip_monte_carlo:
        full_verification_command.append("--skip-monte-carlo")
    if args.skip_pi_package:
        full_verification_command.append("--skip-pi-package")

    planned_stages: list[tuple[str, list[str], dict[str, str] | None]] = [
        (
            "source_cleanliness",
            [sys.executable, str(CHECK_SOURCE_CLEANLINESS)],
            None,
        ),
        ("full_verification", full_verification_command, None),
    ]

    if not args.quick:
        sanitizer_build = REPO_ROOT / "build-assurance-sanitizers"
        planned_stages.extend(
            [
                (
                    "configure_sanitizers",
                    [
                        "cmake",
                        "-S",
                        ".",
                        "-B",
                        str(sanitizer_build),
                        "-DCMAKE_BUILD_TYPE=Debug",
                        "-DASTRA_WARNINGS_AS_ERRORS=ON",
                        "-DASTRA_ENABLE_SANITIZERS=ON",
                    ],
                    None,
                ),
                (
                    "build_sanitizers",
                    ["cmake", "--build", str(sanitizer_build), "--parallel"],
                    None,
                ),
                (
                    "test_sanitizers",
                    [
                        "ctest",
                        "--test-dir",
                        str(sanitizer_build),
                        "--output-on-failure",
                    ],
                    {
                        "ASAN_OPTIONS": "detect_leaks=1:halt_on_error=1:strict_string_checks=1",
                        "UBSAN_OPTIONS": "halt_on_error=1:print_stacktrace=1",
                    },
                ),
                (
                    "controlled_mutation",
                    [sys.executable, str(REPO_ROOT / "tools" / "run_controlled_mutation.py")],
                    None,
                ),
            ]
        )

    try:
        for name, command, environment in planned_stages:
            commands_executed.append(command)
            result = run_stage(name, command, environment=environment)
            results.append(result)
            if not result.passed:
                overall_status = "failed"
                break
    except (OSError, KeyboardInterrupt) as error:
        overall_status = "failed"
        print(f"ERROR: assurance workflow interrupted: {error}")
    finally:
        write_summary(
            results,
            overall_status=overall_status,
            requested_quick_mode=args.quick,
        )
        manifest_code = generate_manifest(
            verification_status=overall_status,
            commands=commands_executed,
            sanitizers_enabled=sanitizer_requested,
        )
        if manifest_code != 0:
            overall_status = "failed"
            print("ERROR: provenance manifest generation failed.")
            write_summary(
                results,
                overall_status=overall_status,
                requested_quick_mode=args.quick,
            )

    print()
    print(f"Assurance status: {overall_status.upper()}")
    print(f"Summary: {SUMMARY_PATH.relative_to(REPO_ROOT)}")
    print(f"Manifest: {MANIFEST_PATH.relative_to(REPO_ROOT)}")
    return 0 if overall_status == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
